language: rust
services:
  - docker
git:
  depth: 1
branches:
  only:
    - master
matrix:
    include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
          - libxcb-shape0-dev
          - libxcb-xfixes0-dev
    - os: windows
rust:
  - nightly
install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: XgM0Om8ZX+9mtfltzZgKoHSFzKFWEn0QsWiOfl6mReilHvFAfWlG22vK+KRKDc+RpDiVhXgUX8Y6RSVJlsDtoPAofLTY59wp1NUsT0Cvuj+uUo4z1ki1Ab0tfv9tbVNSJJUs9BDERkxLecPSrKGm0nI6tkhVP8ohcO+DoCnuK/P0SdzEinZ29jx/IzCQA65DQ05EZEbrqnPt0PWG2TqWtQULuwS7sKqqPB/pSY7vTh5Gnr2kZzGJSSgDz6538UJ7LEFJcDlG9vr1+EkDNwS0+q3E0s8gPCFxAqiGw1n3KdT6GiAHMfPGQXvNSdmUcR/ZZUBZzTIwuCQblf8L5i5J2CFmVmADfYNlt7x6UHDsHtYktOmYF8Z0XE6jSoWz6pCHWYxpNRUqjrp6ENfkkZ1OGGLdsAwnTZZBFMSNxvQ2eiCjfXrvDQ8D0iqXEhTu+6QCNdcefacr1NsKYEcqFw928ci3LjIPHmKiiqknAccKmEF/hGzs0DCfm6DuoPEPkq3Vr05NV3DTQVBqf/GvePcrJ8uCrFdRAAyABosf39MYUPAZh925CSLNamXDgSDzCT2tvKUtmiPCVjNdvIkMo04q2SP6oxLqzSF6BwDtpvzgIigbhXy16G9gdqGX7JosmVQj387JuTdI7CfMzGDf7csNUCmBPQ9DlnkAMq/lpv4rI/I=
  skip_cleanup: true
  file_glob: true
  file: "./target/deploy/*"
  on:
    condition: $CLIPPY != true
    repo: wight554/alacritty
    branch: master
  name: $TRAVIS_OS_NAME-$(date +'%Y%m%d%H%M')-$(git rev-parse --verify --short HEAD)
notifications:
  email:
    on_success: never
    on_failure: always
